version: '3'

services:
  fantasydb:
    image: mariadb:10.3
    container_name: fc-mariadb
    volumes:
      - fantasy-calendar-db:/var/lib/mysql
      - ./setup/database.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fantasy-calendar
    ports:
      - "13306:3306"

  fantasy-calendar:
    container_name: fantasy_calendar
    build: ./setup/nginx/
    user: "1000:1000"
    volumes:
      - ./:/fantasy-calendar:ro
    ports:
      - "9980:8080"

  fantasy-calendar-php:
    container_name: fantasy_calendar_php
    build: .
    user: "1000:1000"
    volumes:
      - ./:/fantasy-calendar
    environment:
      - "APP_ENV=local"
      - "APP_KEY=base64:ECSIURhDQnHBdx7nRVlwGtPwBU+RZrQCQpmGHesaIUM="
      - "APP_DEBUG=true"
      - "APP_URL=http://fantasy-calendar.test:9980/"
      - "COOKIEADDRESS=http://fantasy-calendar.test:9980/"
      - "DB_HOST=fantasydb"
      - "DB_DATABASE=fantasy-calendar"
      - "DB_USERNAME=root"
      - "DB_PASSWORD=root"
      

  fantasy-calendar-composer-install:
    build: .
    user: "1000:1000"
    volumes:
      - ./:/fantasy-calendar
    command: ["/usr/local/bin/php", "/var/www/html/composer.phar", "install", "-d", "/fantasy-calendar/"]

volumes:
  fantasy-calendar-db:
