version: '3'

services:
  fantasydb:
    image: mariadb:10.3
    container_name: fc-mariadb
    volumes:
      - fantasy-calendar-db:/var/lib/mysql
      - ./setup/database.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fantasy-calendar
    ports:
      - "13306:3306"

  fantasy-calendar:
    image: nginxinc/nginx-unprivileged
    container_name: fantasy_calendar
    user: "1000:1000"
    volumes:
      - ./:/fantasy-calendar
      - ./setup/docker.env:/fantasy-calendar/.env
      - ./setup/nginx/fantasy-calendar.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9980:8080"

  fantasy-calendar-php:
    container_name: fantasy_calendar_php
    build: .
    user: "1000:1000"
    volumes:
      - ./:/fantasy-calendar
      - ./setup/docker.env:/fantasy-calendar/.env

  fantasy-calendar-composer-install:
    build: ./setup/php/
    user: "1000:1000"
    volumes:
      - ./:/fantasy-calendar
      - ./setup/docker.env:/fantasy-calendar/.env
    command: ["/usr/local/bin/php", "/var/www/html/composer.phar", "install", "-d", "/fantasy-calendar/"]

volumes:
  fantasy-calendar-db:
