on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@main
      with:
        node-version: '14'
    - name: Composer install
      uses: docker://composer:latest
      with:
        args: install
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Create env file
      run: |
        cat > .env << EOF
        APP_ENV=production
        EOF
    - name: Install NPM dependencies
      run: npm install
    - name: Install NPM dependencies
      run: npm run production
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync ./public s3://fantasy-calendar
    - name: Deploy Serverless
      run: npx serverless deploy -f web
    - name: Deploy Serverless
      run: npx serverless deploy -f artisan
    - name: Deploy Serverless
      run: npx serverless deploy -f worker
    - name: Actions Status Discord
      uses: sarisia/actions-status-discord@v1.5.2
      with:
        webhook: ${{ secrets.DISCORD_FC_BETA_WEBHOOK }}
        description: "A new version of the beta has been deployed"
        username: "Github"
        avatar_url: "https://beta.fantasy-calendar.com//resources/header_logo.png"
