on:
  push:
    branches:
      - master
name: Deploy master branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@main
      with:
        node-version: '14'
    - name: Install Serverless Framework
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Create env file
      run: |
        cat > .env << EOF
        APP_ENV=production
        EOF
    - name: Install NPM dependencies
      run: npm install
    - name: Composer install
      uses: docker://composer:latest
      with:
        args: install
    - name: Deploy Serverless
      run: serverless deploy
